In [1]:
import numpy as np
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd.variable as variable
import random
import time
import torch

In [2]:
game = np.zeros((9,6))
game1 = np.zeros((9,6))
game2 = np.zeros((9,6))
game3 = np.zeros((9,6))
game4 = np.zeros((9,6))
game5 = np.zeros((9,6))
game6 = np.zeros((9,6))
game7 = np.zeros((9,6))

In [3]:
for i in range(9):
    for j in range(6):
        game[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game1[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game2[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game3[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game4[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game5[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game6[i,j] = random.choice([-3,-2,-1,0,1,2,3])
        game7[i,j] = random.choice([-3,-2,-1,0,1,2,3])

In [4]:
game_tensor = torch.from_numpy(game)
game_tensor1 = torch.from_numpy(game1)

In [26]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,1,3,padding=1)
#        self.conv2 = nn.Conv2d(54,2,2)
#        self.fc1 = nn.Linear(56,54)
        
    def forward(self,x):
        x = self.conv1(x)
#        x = self.conv2(x)
#        x = x.view(-1,56)
#        x = self.fc1(x)
        return x

In [27]:
net = Net()
net.double()

Net(
  (conv1): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)

In [28]:
net(game_tensor.view(-1,1,9,6))

tensor([[[[-0.4065, -1.3777, -0.7117,  1.0310,  0.5766, -0.5657],
          [ 1.4918, -1.2335, -0.3641,  2.0793,  0.5985,  0.6906],
          [ 1.8756,  0.5901, -0.5644,  0.4180,  1.3643,  0.3870],
          [ 0.0253,  0.4761,  1.1827, -0.7043, -0.1772,  1.6060],
          [ 0.5090, -0.1465,  1.5238, -0.7480, -0.4228, -0.2096],
          [-0.2063,  1.1727,  1.2098,  1.1927,  1.5809, -0.5995],
          [-1.0056, -0.7063,  1.2886,  0.2907,  1.8246,  0.9271],
          [ 1.2013,  0.3204, -0.3103,  1.5151,  0.7475,  0.5598],
          [ 0.4362,  0.9716, -0.7558,  0.0469,  0.9448,  0.3604]]]],
       dtype=torch.float64, grad_fn=<ThnnConv2DBackward>)

In [10]:
batch = torch.Tensor([game,game1,game2,game3,game4,game5,game6])

In [11]:
objective = nn.CrossEntropyLoss()
optimizer = optim.Adam(params=net.parameters())

In [12]:
game_tensor

tensor([[ 0., -1., -2., -2.,  3.,  1.],
        [ 3.,  3., -3.,  3.,  3.,  2.],
        [ 1.,  3., -3., -2.,  3., -1.],
        [-3.,  1., -1.,  3., -1.,  2.],
        [ 1.,  0.,  1.,  3., -3.,  0.],
        [-3.,  1.,  0.,  3.,  2.,  3.],
        [ 1., -3.,  3.,  0.,  1.,  2.],
        [ 3.,  1.,  0.,  1.,  0.,  1.],
        [-3.,  2., -2., -2.,  0.,  1.]], dtype=torch.float64)

In [35]:
game_tensor[0,0] = 3
game_tensor

tensor([[ 3., -2.,  0.,  1.,  3.,  3.],
        [ 3.,  0., -1., -2.,  3.,  2.],
        [ 1.,  2.,  3., -3.,  0.,  0.],
        [ 2.,  0.,  3.,  3.,  0., -3.],
        [ 1.,  2., -3.,  1., -1., -2.],
        [-2.,  2., -2.,  1., -3.,  3.],
        [ 0.,  3., -1.,  1., -1.,  0.],
        [-1., -2., -2.,  1., -1., -3.],
        [ 2.,  2., -1., -3.,  0., -3.]], dtype=torch.float64)

In [14]:
F.softmax(net(game_tensor.view(-1,1,9,6)))[0]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([0.0213, 0.0220, 0.0211, 0.0251, 0.0372, 0.0148, 0.0221, 0.0246, 0.0136,
        0.0122, 0.0232, 0.0283, 0.0170, 0.0389, 0.0202, 0.0193, 0.0351, 0.0106,
        0.0177, 0.0229, 0.0253, 0.0342, 0.0137, 0.0146, 0.0147, 0.0086, 0.0110,
        0.0076, 0.0268, 0.0089, 0.0128, 0.0227, 0.0127, 0.0244, 0.0150, 0.0189,
        0.0185, 0.0055, 0.0086, 0.0110, 0.0072, 0.0288, 0.0185, 0.0159, 0.0092,
        0.0317, 0.0154, 0.0228, 0.0140, 0.0087, 0.0189, 0.0128, 0.0152, 0.0183],
       dtype=torch.float64, grad_fn=<SelectBackward>)

In [39]:
net(game_tensor.view(-1,1,9,6))

tensor([[ 0.2905, -0.0255, -0.3059,  0.6814,  0.0350,  0.1762,  0.3526, -0.5123,
          0.1447, -0.6922, -0.4696,  0.0970,  0.2543,  0.1365,  0.1489, -0.2115,
          1.4305,  0.2972,  0.2118, -0.1558, -0.5841,  0.3955, -0.0618, -0.4130,
          0.4219,  0.6944, -0.1954, -0.0453, -0.5068, -0.3491,  0.0613, -0.1798,
         -0.2621,  0.1851,  0.1758,  0.8077, -0.0755,  0.2191, -0.2720, -0.6475,
         -0.6176, -0.6752, -0.3089, -0.0059, -0.4131, -0.5647,  0.1412,  1.3426,
          0.4400,  0.6681, -0.2004,  0.1820,  1.1399,  0.1155]],
       dtype=torch.float64, grad_fn=<ThAddmmBackward>)

In [56]:
out = F.softmax(net(game_tensor.view(-1,1,9,6)))
target = torch.autograd.variable(torch.LongTensor([10]))


loss = objective(out,target)

loss.backward()

optimizer.step()
optimizer.zero_grad()

F.softmax(net(game_tensor.view(-1,1,9,6)))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\__init__.py:167: UserWarning: torch.autograd.variable(...) is deprecated, use torch.tensor(...) instead
  warnings.warn("torch.autograd.variable(...) is deprecated, use torch.tensor(...) instead")
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if sys.path[0] == '':


tensor([[0.0135, 0.0119, 0.0179, 0.0202, 0.0261, 0.0137, 0.0166, 0.0122, 0.0123,
         0.0446, 0.0457, 0.0262, 0.0239, 0.0230, 0.0227, 0.0075, 0.0228, 0.0125,
         0.0349, 0.0109, 0.0176, 0.0178, 0.0171, 0.0102, 0.0137, 0.0118, 0.0175,
         0.0219, 0.0113, 0.0117, 0.0154, 0.0172, 0.0120, 0.0235, 0.0114, 0.0217,
         0.0189, 0.0174, 0.0242, 0.0176, 0.0347, 0.0068, 0.0123, 0.0116, 0.0160,
         0.0132, 0.0150, 0.0266, 0.0309, 0.0130, 0.0189, 0.0141, 0.0095, 0.0285]],
       dtype=torch.float64, grad_fn=<SoftmaxBackward>)

In [48]:
net(game_tensor.view(-1,1,9,6))

tensor([[ 0.1724, -0.1602, -0.1393,  0.3736, -0.0419,  0.0132,  0.2545, -0.4734,
         -0.1359,  0.0176, -0.4844,  0.1947,  0.3012,  0.1449,  0.0393, -0.3971,
          1.0427,  0.0598,  0.1746, -0.2909, -0.5954,  0.0371,  0.0812, -0.6049,
          0.1902,  0.2495, -0.3458,  0.1293, -0.5646, -0.3884, -0.0714, -0.0959,
         -0.3360,  0.0163, -0.0253,  0.6013, -0.0984,  0.0640, -0.2774, -0.5442,
         -0.3878, -0.8104, -0.3431, -0.2226, -0.3514, -0.5406,  0.0736,  0.8828,
          0.3260,  0.2379, -0.1305, -0.0281,  0.7098,  0.0324]],
       dtype=torch.float64, grad_fn=<ThAddmmBackward>)

In [47]:
F.softmax(net(game_tensor.view(-1,1,9,6)))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0.0214, 0.0154, 0.0157, 0.0262, 0.0173, 0.0183, 0.0232, 0.0112, 0.0157,
         0.0183, 0.0111, 0.0219, 0.0244, 0.0208, 0.0187, 0.0121, 0.0511, 0.0191,
         0.0215, 0.0135, 0.0099, 0.0187, 0.0195, 0.0098, 0.0218, 0.0231, 0.0128,
         0.0205, 0.0102, 0.0122, 0.0168, 0.0164, 0.0129, 0.0183, 0.0176, 0.0329,
         0.0163, 0.0192, 0.0137, 0.0105, 0.0122, 0.0080, 0.0128, 0.0144, 0.0127,
         0.0105, 0.0194, 0.0436, 0.0250, 0.0229, 0.0158, 0.0175, 0.0366, 0.0186]],
       dtype=torch.float64, grad_fn=<SoftmaxBackward>)

In [45]:
game_tensor[0,0] = 1

In [46]:
game_tensor

tensor([[ 1., -2.,  0.,  1.,  3.,  3.],
        [ 3.,  0., -1., -2.,  3.,  2.],
        [ 1.,  2.,  3., -3.,  0.,  0.],
        [ 2.,  0.,  3.,  3.,  0., -3.],
        [ 1.,  2., -3.,  1., -1., -2.],
        [-2.,  2., -2.,  1., -3.,  3.],
        [ 0.,  3., -1.,  1., -1.,  0.],
        [-1., -2., -2.,  1., -1., -3.],
        [ 2.,  2., -1., -3.,  0., -3.]], dtype=torch.float64)